### ISSUE TITLE
[Released] PlutoGrid Next Version Work Sharing. 5.0.0

### ISSUE THREAD

**Issue by bosskmk** [bosskmk/pluto_grid#388]
- [x] Added middle divider for `PlutoDualGrid`, `PlutoDualPopup` widget.
  By adding a divider in the center of the two grids, the position can be changed by dragging and dropping.
- [X] Add to `PlutoGridEventManager` stream to receive column sort changes.
  #467
  - Add `PlutoGrid.onSorted` callback.
- [x] Added an option to disable column width adjustment while displaying the column right menu.
  #465
  - Activate both `PlutoColumn.enableContextMenu` and `PlutoColumn.enableDropToResize`
    Tap the column menu to display the context menu. Drag left or right to adjust the column width.
  - Activate only `PlutoColumn.enableContextMenu`
      You cannot adjust the column width by dragging the column menu.
  - Only enable `PlutoColumn.enableDropToResize`
      You cannot call the context menu by tapping the column menu.
- [x] Hide all column headings.
  https://github.com/bosskmk/pluto_grid/issues/455#issuecomment-1147033828
- [ ] Dropdown autocomplete for column filtering
  #288
  #414
- [x] Improved left-right scrolling performance.
  When moving left and right scrolling heavily in profile mode in the Android emulator, it was improved from an average of 20 ms/frame in the past to an average of 10 ms/frame after improvement.
  https://github.com/bosskmk/pluto_grid/issues/446#issuecomment-1152772321
  https://github.com/bosskmk/pluto_grid/issues/468#issuecomment-1152773676
- [x] When the parent widget of `PlutoGrid` is scrolled, in the previous 4.0.0 logic, the error that the row area disappears when the column is out of the screen area has been fixed.
- [x] Improve text selection when edit TextCell by @DmitrySboychakov
  #469
- [x] Improve padding for table cells and column titles by @DmitrySboychakov
  #470
- [x] Display a scroll bar when moving the horizontal axis with the keyboard.
- [x] Changing the way columns are moved by dragging them.
  Previously, it was changed immediately in the onDragUpdate state.
  Changed in onDragEnd state in the changed version. Change the background color of the column to be moved instead. 
  (`PlutoGridStateManager.dragTargetColumnColor`)
- [x] Modified to pass `PlutoColumn` instead of passing `PlutoColumn.key` when calling `hideColumn`.
- [x] Add `hideColumns(List<PlutoColumn> columns, bool hide)`;
- [x] Changes due to the constraint of a frozen column.
   - The width of the frozen column cannot be expanded beyond the limit width.
   - When changing a non-frozen column to a frozen column, it cannot be changed if the constraint width is insufficient.
   - If a column with a hidden frozen column state is unhidden in a narrow constraint width, the column frozen state is forcibly changed to `PlutoColumnFrozen.none`.
   - If the entire grid width is narrowed to less than the constraint width while there is a frozen column, the frozen column is permanently changed to `PlutoColumnFrozen.none`, and it does not return to the frozen column again even if the grid width is increased.
- [x] Change the logic to move by dragging rows.
  Previous behavior: rows are moved while dragging.
  Changed behavior: It does not move while dragging, but moves only when you mouse-up or tap-up.
- [x] Changed logic for scrolling when dragging rows, column or selecting rows or cells.
`Previous version`: Scrolling continues only when the pointer is moved continuously so that the move event of the mouse (tab) continues to occur
   `Changed version`: If the move event of the mouse (tab) occurs only once, the scroll event continues in the scroll direction. The scroll animation continues to the end of the scroll direction even if the move event is not triggered by continuously moving the pointer.
   The scroll animation stops when the pointer enters a grid that does not require scrolling or when a MouseUp(PointerUp) event is fired.
- [x] [Expand Columns to cover the parent Container Width](https://github.com/bosskmk/pluto_grid/issues/262#)
- [x] Support RTL https://github.com/bosskmk/pluto_grid/pull/394
  Changed left and right of `PlutoColumn.frozen` to start and end.
  `PlutoColumn.textAlign` default value changed from left to start.
  `PlutoColumn.titleTextAlign` default value changed from left to start. 
  Translation needed. https://www.reddit.com/r/flutterhelp/comments/vsj7jc/i_need_translation_help_from_the_open_source/
- [x] Change `PlutoGridConfiguration`.
  Settings such as color, size, icon, border, and text style have been moved to `PlutoGridConfiguration.style`.
- [x] Even/Odd Color https://github.com/bosskmk/pluto_grid/issues/475
  Add `PlutoGridConfiguration.style.oddRowColor`, `PlutoGridConfiguration.style.evenRowColor`.
- [x] Set default row color #489 
  Add `PlutoGridConfiguration.style.rowColor`.
- [x] Customize column menu #478

**Comment by bosskmk** [comment]
This is a link where you can test the 4.1.0 version.
https://weblaze.dev/pluto_grid/build/pre/web/#/

**Comment by kiaxseventh** [comment]
Can you tell the release date ?

**Comment by bosskmk** [comment]
@kiaxseventh 
Feature development is almost complete.
Odd/Even Color of rows is left, but it will be finished soon.
However, it is necessary to write tests and test code and fix any bugs found.

Are you an RTL user?
If so, can you test the RTL related functions from the preview link above?

In case of RTL, the current behavior is as below.
* Move the currently focused cell
   - Horizontal arrow keys work in reverse
   - Home, End, Tab, Shift-Tab keys work in reverse

**Comment by kiaxseventh** [comment]
> @kiaxseventh , @ZeraW Feature development is almost complete. Odd/Even Color of rows is left, but it will be finished soon. However, it is necessary to write tests and test code and fix any bugs found.
> 
> Are you an RTL user? If so, can you test the RTL related functions from the preview link above?
> 
> In case of RTL, the current behavior is as below.
> 
> * Move the currently focused cell
>   
>   * Horizontal arrow keys work in reverse
>   * Home, End, Tab, Shift-Tab keys work in reverse

i tested it. It worked for me.
It doesn't have any problem Every thing is ok

**Comment by bosskmk** [comment]
@kiaxseventh 
Thank you for your confirmation.
The next version is likely to be distributed within 1-2 weeks.
But I'm not sure.
I'll let you know here when it's released.

**Comment by bosskmk** [comment]
PlutoGrid 5.0.0 has been deployed.
There are other changes from version 4, so please check the ChangeLog.
https://pub.dev/packages/pluto_grid/changelog#500---2022-7-11

The demo page has also been updated.
https://weblaze.dev/pluto_grid/build/web/#/
